### ISSUE TITLE
refactor shutdown sequence to use plugin.stop

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-input-perfmon#2]
Change shutdown sequence to be triggered by plugin.stop instead of ShutdownSignal exception.
Also remove any calls to: shutdown, finished, finished?, running? or terminating?
This depends on https://github.com/elastic/logstash/pull/3895

**Comment by NickMRamirez** [comment]
How does this apply? I only use `teardown` during shutdown of the plugin.

**Comment by suyograo** [comment]
@NickMRamirez see https://github.com/elastic/logstash/issues/3210#issuecomment-139284570 for details

**Comment by untergeek** [comment]
There is no code here.  This will be addressed in forks, or when something is merged here.
